### PR TITLE
revert remacs version to 26.2

### PR DESCRIPTION
**Pull request by ngortheone**
@shaleh 

Closes:
https://github.com/remacs/remacs/issues/1521

Partially fixes
https://github.com/remacs/remacs/issues/1513

### CODE REVIEW

**Comment by shaleh** [comment]
I would like to see us revert the changelog and other bits back too. Which will also help with the merges from emacs.

**Comment by ngortheone** [comment]
Surprisingly this tiny change break a lot of things..

**Comment by ngortheone** [comment]
What "other bits" have to be reverted in order to achieve parity with 26.2?

**Comment by shaleh** [comment]
I *think* that is all. Changelog, some docs. I suspect everything else is all ok.

An interesting thing to do would be to look at the difference between https://github.com/emacs-mirror/emacs/tree/emacs-26 and remacs tree.

**Comment by ngortheone** [comment]
I have a suspicion that someone else broke tests... Previous commit fails `make check` too

**Comment by ngortheone** [comment]
I did take a look at the difference between remacs and https://github.com/emacs-mirror/emacs/tree/emacs-26 
And the difference seems huge (maybe to my untrained eye). It looks like we missed a whole lot of patches. See my rant on gitter..

**Pull request merged**
