### PR TITLE
Port frame-font-cache.

### LINKED ISSUE #1398: Port frame-font-cache
```c
DEFUN ("frame-font-cache", Fframe_font_cache, Sframe_font_cache, 0, 1, 0,
       doc: /* Return FRAME's font cache.  Mainly used for debugging.
If FRAME is omitted or nil, use the selected frame.  */)
  (Lisp_Object frame)
{
#ifdef HAVE_WINDOW_SYSTEM
  struct frame *f = decode_live_frame (frame);

  if (FRAME_WINDOW_P (f))
    return FRAME_DISPLAY_INFO (f)->name_list_element;
  else
#endif
    return Qnil;
}
```

Search for `#[cfg(feature = "window-system")]` in our code base to port this function.

### PR DESCRIPTION
**Pull request by cantsin**
Closes #1398.

Not sure how to add tests here, some pointers would be appreciated.

### CODE REVIEW

**Comment by brotzeit** [comment]
Thanks for the PR! I just realized we need to add `FONT_DEBUG` for this function.

**Comment by cantsin** [comment]
Sure, I can add `FONT_DEBUG` into here if that makes sense.

**Comment by brotzeit** [comment]
I actually doubt it makes sense. It isn't defined in configure.ac. Instead it's defined this way:

```c
#ifndef FONT_DEBUG
#define FONT_DEBUG
#endif
```

Looks odd to me ?

**Comment by brotzeit** [comment]
Looks to me like we can remove this completely...

**Comment by cantsin** [comment]
O_o that is weird. Alright then, removing.

Tangential question, how do we sync up with emacs code? Would removing `FONT_DEBUG` make it harder to sync up later?

**Comment by brotzeit** [comment]
I don't think so since the affected files don't get changed frequently.

**Pull request merged**
