### PR TITLE
Fix ARM aarch64 error

### PR DESCRIPTION
**Pull request by jamcha-aa**
Fix errors of [#1393](https://github.com/remacs/remacs/issues/1393).

### CODE REVIEW

**Comment by shaleh** [comment]
An annoyance with the current `rustup` is it does not automatically update installed components.
We need to run this whenever the version in `rust-toolchain changes: `rustup component add rustfmt-preview`. Otherwise you have the wrong version of rustfmt. Also, set `(setq rust-format-on-save t)` in your (r)emacs config and rust mode will call rustfmt whenever you save.

BTW, rustup is smart and will try to run the correct version of rustfmt based on the configuration of your current project. So do not worry about having conflicting versions installed as long as all were installed with `rustup component add`.

**Comment by shaleh** [comment]
The change looks reasonable though. Let's see what @MarcusE1W says.

**Comment by shaleh** [comment]
@jamcha-aa I hand edited the PR so the rest of the tests can run. If you need to make updates, be sure to pull first.

BTW, it is good practice to make a branch for each PR instead of committing to master in your own repo. This lets you work on multiple items and reduces the chance of messing up your local tree.

**Comment by jamcha-aa** [comment]
Thanks @shaleh  I will split the branch and develop it before making future PRs.

**Comment by MarcusE1W** [comment]
Happy to report that the 'jamcha-aa:master' branch works on my Pinebook.

**Comment by jamcha-aa** [comment]
Thanks for merging. I'd be happy to test out PRs for supporting ARM architectures.

**Pull request merged**
