### PR TITLE
Cut is_nil, impl Not for LispObject

### PR DESCRIPTION
**Pull request by nickdrozd**

### CODE REVIEW

**Comment by shaleh** [comment]
I want to like this. But `is_not_nil` stops me. This leads to confusion where the positive is written one way and the negative completely differently.

I'd rather write == Qnil and == Qt than have this as long the positive is more complicated.

**Comment by nickdrozd** [comment]
I have another commit that more or less converts every instance of `is_not_nil` to `into`. I wish there was a way to have it automatically convert in boolean contexts. The asymmetry is very annoying.

**Comment by nickdrozd** [comment]
We can leave it up for a while and see what we can come up with.

**Comment by shaleh** [comment]
I supposed we could be like the Javascript community and use `!!foo`. Ick.

**Comment by agraven** [comment]
I mean, it's not *that* much worse that rusts `&*` :p

**Comment by nickdrozd** [comment]
I posted this question to Rust Reddit: https://www.reddit.com/r/rust/comments/ah7b2d/automatic_boolean_casting/

**Comment by brotzeit** [comment]
I think the type indication is worth the verbosity. Our goal is to eventually remove nil from rust as far as possible right ?

**Comment by nickdrozd** [comment]
PR is out of date, so closing in favor of https://github.com/remacs/remacs/issues/1450

**Pull request closed without merging**
