### PR TITLE
Rollup to 2a1fe08307

### PR DESCRIPTION
**Pull request by brotzeit**

### CODE REVIEW

**Comment by brotzeit** [comment]
I wonder if we can just keep `TEST_LOAD_EL ?= yes`...

**Comment by brotzeit** [comment]
@shaleh What do you think ?

**Comment by shaleh** [comment]
I need to look at it. Good work identifying the TEST_LOAD_EL change. I am unlikely to look at this for a couple of days.

**Comment by brotzeit** [comment]
#1472

**Pull request closed without merging**
